Git notes support
distrust-foundation/sig pull request #1
Opened 2023-01-19 22:07 UTC by lrvick

To review:

1. Run test suite
    ```
   make test
    ```
2. Read code
3. Verify signatures
   ```
   sig verify
   ```
4. Add/push own signature
    ```
    sig add --push
    ```

2023-01-20 02:24 UTC, daurnimator requested changes

2023-01-20 02:24 UTC, daurnimator commented on README.md
> +      Using sig to verify the signatures of sig itself is not recommended.
```suggestion
      Using `sig` to verify the signatures of `sig` itself is not recommended.
```

2023-01-20 02:24 UTC, daurnimator commented on README.md
> +          <(printf $line | sed 's/pgp:.*/pgp/g'); \
```suggestion
          <(printf "$line" | sed 's/.*pgp://g'| openssl base64 -d -A) \
          <(printf "$line" | sed 's/pgp:.*/pgp/g'); \
```

2023-01-20 02:24 UTC, daurnimator commented on README.md
> +  3. Copy to $PATH
```suggestion
  3. Copy to `$PATH`
```

2023-01-20 02:24 UTC, daurnimator commented on README.md
> +  * Verify m-of-n signatures by given group are present for a git repo or ref
What does "for a git repo" mean?

2023-01-20 02:24 UTC, daurnimator commented on sig
> +readonly DATE=$(command -v gdate || command -v date)
```
         ^--^ SC2034 (warning): DATE appears unused. Verify use (or export if used externally).
         ^--^ SC2155 (warning): Declare and assign separately to avoid masking return values.
```

2023-01-20 02:24 UTC, daurnimator commented on sig
> +			find . -type f -not -path "./.git/*" \
Need to use null separation here

2023-01-20 02:24 UTC, daurnimator commented on sig
>  			group_check_fp "${seen_fp}" "${group}" || {
```
                                        ^--------^ SC2154 (warning): seen_fp is referenced but not assigned (did you mean 'seen_fps'?).
```

2023-01-20 02:24 UTC, daurnimator commented on sig
> +	local fps="" git_sig_raw code=1
```
              ^-^ SC2034 (warning): fps appears unused. Verify use (or export if used externally).
                     ^---------^ SC2034 (warning): git_sig_raw appears unused. Verify use (or export if used externally).
```

2023-01-20 02:24 UTC, daurnimator commented on sig
> +	local sig_count=0 seen_fps="" fp="" tag_fps="" note_fps=""
```
                                            ^-----^ SC2034 (warning): tag_fps appears unused. Verify use (or export if used externally).
                                                       ^------^ SC2034 (warning): note_fps appears unused. Verify use (or export if used externally).
```

2023-01-20 02:24 UTC, daurnimator commented on sig
> +		|| die "Error: This folder is not a git repository"
so `sig` only supports git now?

2023-01-20 08:58 UTC, lrvick commented on README.md
> +  * Verify m-of-n signatures by given group are present for a git repo or ref
better phrasing may be "for the current HEAD or a specific references" but trying to be short and simple.

2023-01-20 08:59 UTC, lrvick commented on sig
> +	[ -d .git ] \
Good catch.

2023-01-20 09:06 UTC, lrvick commented on sig
> +		|| die "Error: This folder is not a git repository"
The old detached functionality which requires making a commit was never used by anyone as the workflow is kind of awful.

Git notes resolves the problem detached was meant to solve of people who don't have access to a repo directly being able to add notes, since you can merge notes from a fork.

I also don't want to support two different signing schemes and anything I don't plan to bring with me to an alternate language implementation (planning on rust next), so overall this is just going to be "git-sig" which will be able to function as a git addon easily.

The new sig format also uses a tree hash that is git agnostic, so I do think I can do a separate toplevel tool or standalone command that generates these as simple text files for a given directory that can be uploaded anywhere if there is demand for this in the future.

2023-01-20 09:53 UTC, singlerider reviewed
```shell
sig add --push
```

results in  `ERROR: Permission to distrust-foundation/sig.git denied to singlerider.`

Looks like I'll need escalated permissions.

2023-01-20 10:19 UTC, daurnimator commented on sig
> +		|| die "Error: This folder is not a git repository"
From the README: 
> The simple GPG signature toolchain for directories or git repos.

This check seems to be failing out if you're not in a git repo; so how is `sig` "for directories"?

2023-01-20 12:54 UTC, singlerider commented
> 

I re-read the comments. The instructions should have suggested requiring a fork. I'll try that.

2023-01-20 13:08 UTC, singlerider requested changes
```shell
sig add --push
```

is not ideal, because if a `push` operation fails, the old signature remains locally, not pushed. The next time it's run, if successful, will push two `sig`s. Should a user be able to just:

```shell
sig push
```

?

2023-01-20 21:01 UTC, singlerider commented on README.md
> +`
Is this single backtick a mistake?

2023-01-26 02:03 UTC, lrvick commented on sig
> +		|| die "Error: This folder is not a git repository"
reworded

2023-01-26 02:11 UTC, lrvick commented
@singlerider I don't want to feature creep and fully handle forks and signature import/export on this branch just yet, but can tackle that in some follow up PRs.

I think I addressed everything else related to the current in-scope functionality though.

2023-01-26 12:14 UTC, daurnimator requested changes

2023-01-26 12:14 UTC, daurnimator commented on sig
> +	[[ "$push" -eq "0" ]] || $PROGRAM push
```suggestion
	[[ "$push" -eq "0" ]] || "$PROGRAM" push
```

2023-01-26 12:14 UTC, daurnimator commented on sig
> +    git notes --ref signatures merge -s cat_sort_uniq origin/signatures
Indentation

2023-01-26 12:14 UTC, daurnimator commented on sig
> +    git fetch origin refs/notes/signatures:refs/notes/origin/signatures
Don't assume `origin`: people frequently use other names for their remotes.

2023-01-26 12:14 UTC, daurnimator commented on test/test.bats
> +    set_identity "user3"
Indentation

2023-01-27 06:37 UTC, daurnimator commented on sig
> +	[ -d .git ] || [ -L .git ] || [ -f .git ] \
Use `git rev-parse --git-dir` to find this out

2023-01-27 06:38 UTC, daurnimator commented on sig
> +	[ -d '.git' ] \
Use `git rev-parse --git-dir`

2023-01-27 06:39 UTC, daurnimator commented on sig
> +		*) sign_note "$push" ;;
this seems weird. should this whole `case` be removed?

2023-01-27 22:54 UTC, lrvick commented on sig
> +			find . -type f -not -path "./.git/*" \
I want signatures to be able to be exported and verified even without git present in the future.

find is easier for me to predict, and replicate in other languages, than relying on a git built-in.

2023-01-27 22:56 UTC, lrvick commented on sig
> +    if [[ $(git diff --stat) != '' ]]; then
Weird is not a concrete suggestion.

2023-01-27 22:57 UTC, lrvick commented on sig
> +    git fetch origin refs/notes/signatures:refs/notes/origin/signatures
any alternative suggestions?

2023-01-27 22:58 UTC, lrvick commented on sig
> +	[ -d .git ] || [ -L .git ] || [ -f .git ] \
Per above, I don't want git to be required to verify signatures.

2023-01-27 22:59 UTC, lrvick commented on sig
> +	[ -d '.git' ] \
Per above, I don't want git to be required to verify signatures.

2023-03-29 20:49 UTC, lrvick commented on sig
> +			find . -type f -not -path "./.git/*" \
Okay. There are third party implementations of the git tree algorithm, and if I go down the path of our own custom one I will have to implement .gitignore handling etc etc and... yeah.

Just using git tree-hash for now and will revisit this later.

2023-03-29 20:50 UTC, lrvick commented on sig
> +    if [[ $(git diff --stat) != '' ]]; then
we hit 80 char wrap, and I always continue a line at one indent so it is obvious that it is a continuation of the previous line and not a standalone command.

2023-03-29 21:41 UTC, lrvick commented on sig
> +	[ -d '.git' ] \
okay. this tool is git only at this point. Fair.

2023-03-29 21:42 UTC, lrvick commented on sig
> +	[ -d .git ] || [ -L .git ] || [ -f .git ] \
okay. this tool is git only at this point. Fair.

2023-03-29 22:34 UTC, merged

2023-04-09 04:07 UTC, daurnimator commented on sig
> +    if [[ $(git diff --stat) != '' ]]; then
you mixed tabs and spaces.